[tool.poetry]
name = "neo-bot"
version = "0.1.0"
description = "a simple python bot whatsapp"
authors = ["mhmmdo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
neonize = "^0.0.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
